version: "3.9"

services:
  n8n:
    container_name: n8n
    build:
      context: .
      dockerfile: Dockerfile.n8n
    restart: unless-stopped
    environment:
      - WEBHOOK_URL=${URL}        # keep full https URL
      - N8N_HOST=${HOSTNAME}
      - N8N_PORT=5678
      - TZ=${TIMEZONE}
      - GENERIC_TIMEZONE=${TIMEZONE}
      - N8N_ENCRYPTION_KEY=super-secret-key
    networks:
      - n8n-network
    volumes:
      - n8n_data:/home/node/.n8n
      - ./scripts:/workspace
    # optional local debug access (not required for ngrok):
    # ports:
    #   - "5678:5678"
    #   - "5010:5010"

  edge:                            # <— NEW reverse proxy
    image: nginx:alpine
    container_name: edge
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - n8n-network
    # optional local debug: expose 8080
    # ports:
    #   - "8080:8080"

  ngrok:
    container_name: ngrok
    image: ngrok/ngrok:latest
    restart: unless-stopped
    environment:
      - NGROK_AUTHTOKEN=${NGROK_TOKEN}
    command: ["start", "--all", "--config", "/etc/ngrok.yml"]
    networks:
      - n8n-network
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml:ro

volumes:
  n8n_data:

networks:
  n8n-network:
    driver: bridge
